name: Release web app

on:
  push:
    tags:
      - 'web/v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  Invoke-Build-webapp:
    name: Build web app
    uses: ./.github/workflows/ci.yml
  Upload-webapp:
    name: Release web app
    runs-on: ubuntu-latest
    needs: Invoke-Build-webapp
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo tag name
        run: echo "Tag name - ${{github.ref_name}}"
      - name: Download webapp build artifacts
        uses: actions/download-artifact@v4
        with:
          name: webApp
          path: release/
      # changes the base-tag in index.html from '/' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/happyPath\/" \/>/g' release/wwwroot/index.html
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7
        with:
          branch: gh-pages
          folder: release/wwwroot
      - name: Release
        uses: softprops/action-gh-release@v2.3
        with:
          files: ./release/wwwroot/**